<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests\**" />
    <Compile Remove="godot_integration\**" />
    <Compile Remove="godot_project\**" />
    <Compile Remove="game_logic\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="game_logic\GameLogic.csproj" />
  </ItemGroup>

</Project>
